name: GeoHeatFlex
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - atlite
  - xarray
  - matplotlib
  - rioxarray
  - rasterio
  - geopandas
  - rasterstats
  - numpy < 1.23
  - openpyxl
  - spyder-kernels
  - scipy
  - python < 3.10
